name: CI

on:
    pull_request:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: '16'
            - name: Install dependencies
              run: yarn install
            - name: Typecheck
              run: yarn typecheck
            - name: Run tests
              run: yarn test